AWSTemplateFormatVersion: '2010-09-09'
Resources:
  FileUploadBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: 'your-upload-bucket'
      LifecycleConfiguration:
        Rules:
          - Status: 'Enabled'
            ExpirationInDays: 1
